### ISSUE TITLE
Предложение по архитектуре

### ISSUE THREAD

**Issue by SkyQuant** [zamgi/lingvo--PosTagger-ru#2]
Можно ли добавить в решение консольное приложение или юнит-тест, а набор словарей вынести в отдельный проект? Из веб-проекта не совсем понятно как передать текст и вернуть последовательность токенов.

**Comment by zamgi** [comment]
ну,  из веб-проекта, по моему, очень понятно как передать текст и вернуть последовательность токенов. добавить в решение консольное приложение можно. насчет набор словарей вынести в отдельный проект не понял - о какой части речь, как об отдельном проекте?

**Comment by SkyQuant** [comment]
А если вдруг на свете ещё остались такие люди, которым не "очень понятно" :-), можно для них вывести на заглавную раздел, что-то вроде Getting started.

**Comment by SkyQuant** [comment]
Ага, консоль увидел.
Судя по этому выводу, приложение обращается к ресурсам веб-приложения. Можно ли убрать зависимость от фронт-эндового уровня и вынести все словари в отдельный сервис, чтобы мухи были отделены от котлет?
```
elapsed: 00:00:01.9675984, ../../pos-tagger_ru.web.demo/[resources]/morphology/RUS/MorphoTypes.txt
elapsed: 00:00:00.0179632, ../../pos-tagger_ru.web.demo/[resources]/morphology/ENG/MorphoTypes.txt
elapsed: 00:00:01.1868974, ../../pos-tagger_ru.web.demo/[resources]/morphology/RUS/dic_proper.txt
elapsed: 00:00:00.4032213, ../../pos-tagger_ru.web.demo/[resources]/morphology/ENG/dic_proper.txt
elapsed: 00:00:05.5433068, ../../pos-tagger_ru.web.demo/[resources]/morphology/RUS/dic_nominal.txt
elapsed: 00:00:00.7296986, ../../pos-tagger_ru.web.demo/[resources]/morphology/ENG/dic_nominal.txt
```

**Comment by zamgi** [comment]
Судя по этому выводу, приложение обращается не к ресурсам веб-приложения, а просто к ресурсам. ресурсы лежат в каталоге веб-приложения для того, что "подыграть" бесплатному хостингу, который я нашел, для демо в виде веб-приложения.
никаких зависимостей от фронт-эндового уровня нет.

**Comment by zamgi** [comment]
"вынести все словари в отдельный сервис, чтобы мухи были отделены от котлет?" 
- вы когда говорите "словари" вы о чем именно говорите, о каких словарях?

**Comment by SkyQuant** [comment]
содержимое папки [resources]

**Comment by SkyQuant** [comment]
А в качестве дополнительной фичи адекватный синонимайзер не пробовали подключать?

**Comment by zamgi** [comment]
это и есть всё - отдельный проект)))

**Comment by zamgi** [comment]
что такое синонимайзер, да ещё и адекватный ?

**Comment by SkyQuant** [comment]
это когда к лемме привязывается последовательность синонимов

**Comment by SkyQuant** [comment]
а также поиск для 2-3-4-грамм токена-синонима в одно слово

**Comment by zamgi** [comment]
можно даже, в качестве дополнительной фичи, прикрутить автоматическую отправку поздравления бабушке на её день рождения. и много чего ещё.
вы понимаете какую задачу решает именно этот инструмент?

**Comment by SkyQuant** [comment]
сделать приятно бабушке!

**Comment by zamgi** [comment]
вот именно. если бабушке уже приятно, то не трогай её или найди другую бабушку и делай приятно ей. всё просто.
"а также поиск для 2-3-4-грамм токена-синонима в одно слово" - это какая-то другая задача. содержательно с этой не связанная. ясно?
